CREATE DATABASE `spring_data_demo` DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

USE `spring_data_demo`;

DROP TABLE IF EXISTS `article`;

CREATE TABLE `article`
(
    `id`          INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `author`      VARCHAR(255) COLLATE UTF8MB4_BIN DEFAULT NULL COMMENT '作者',
    `createTime` DATETIME                         DEFAULT NULL COMMENT '创建时间',
    `title`       VARCHAR(255) COLLATE UTF8MB4_BIN DEFAULT NULL COMMENT '标题',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = UTF8MB4
  COLLATE = UTF8MB4_BIN
  ROW_FORMAT = DYNAMIC;
